# Site settings
title: Al Johri
email: al.johri@gmail.com
description: >
  Senior Data Scientist | ML Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aljohri.github.io" # the base hostname & protocol for your site
twitter_username: AlJohri
github_username:  AlJohri
linkedin_username: https://www.linkedin.com/in/aljohri

# facebook_username: al.johri

# https://bitbucket.org/aljohri
# https://venmo.com/Al-Johri
# https://cash.me/$AlJohri
# https://www.youtube.com/user/aljohri
# https://www.instagram.com/aljohri/
# http://devpost.com/AlJohri
# https://angel.co/al-johri
# https://trello.com/aljohri
# https://www.producthunt.com/@aljohri
# https://coderwall.com/AlJohri
# https://www.f6s.com/aljohri
# https://soundcloud.com/al-johri
# http://www.last.fm/user/aljohri
# https://livestream.com/accounts/5137189
# http://www.rpubs.com/aljohri/
# https://myspace.com/159122455
# https://www.pinterest.com/aljohri/
# https://www.scribd.com/user/3357261/Al-Johri
# http://www.tonymacx86.com/members/al-johri/

# https://www.bountysource.com/people/37338-aljohri
# https://gratipay.com/~AlJohri/

# http://fivethirtyeight.com/contributors/al-johri/
# https://knightlab.northwestern.edu/author/atul-johri/
# https://generalassemb.ly/instructors/al-johri/8372
# http://www.northbynorthwestern.com/author/aljohri/

# about me
# http://dailynorthwestern.com/tag/al-johri/

# Build settings
markdown: kramdown

collections:
  projects:
    output: true

gems:
- octopress-debugger