# Site settings
title: Al Johri
email: al.johri@gmail.com
description: >
  Software Engineer | Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aljohri.github.io" # the base hostname & protocol for your site
twitter_username: aljohri
github_username:  aljohri
# facebook_username: al.johri

# Build settings
markdown: kramdown

collections:
  projects:
    output: true

gems:
- octopress-debugger